/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/wanghuaijin/Documents/VuePress-Site/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-835237c2",
    path: "/vuepress-site/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-835237c2").then(next)
    },
  },
  {
    path: "/vuepress-site/index.html",
    redirect: "/vuepress-site/"
  },
  {
    path: "/",
    redirect: "/vuepress-site/"
  },
  {
    name: "v-7dd379a2",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7dd379a2").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-c1190922",
    path: "/en/photography/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c1190922").then(next)
    },
  },
  {
    path: "/en/photography/index.html",
    redirect: "/en/photography/"
  },
  {
    path: "/en/Photography/",
    redirect: "/en/photography/"
  },
  {
    name: "v-6ef466ec",
    path: "/en/gtd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ef466ec").then(next)
    },
  },
  {
    path: "/en/gtd/index.html",
    redirect: "/en/gtd/"
  },
  {
    path: "/en/Reading/GTD.html",
    redirect: "/en/gtd/"
  },
  {
    name: "v-f96ef6c4",
    path: "/en/afterwork/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f96ef6c4").then(next)
    },
  },
  {
    path: "/en/afterwork/index.html",
    redirect: "/en/afterwork/"
  },
  {
    path: "/en/Photography/AfterWork.html",
    redirect: "/en/afterwork/"
  },
  {
    name: "v-2a808650",
    path: "/en/vipassana/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a808650").then(next)
    },
  },
  {
    path: "/en/vipassana/index.html",
    redirect: "/en/vipassana/"
  },
  {
    path: "/en/Photography/Vipassana.html",
    redirect: "/en/vipassana/"
  },
  {
    name: "v-7e43dee2",
    path: "/en/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e43dee2").then(next)
    },
  },
  {
    path: "/en/web/index.html",
    redirect: "/en/web/"
  },
  {
    path: "/en/Web/",
    redirect: "/en/web/"
  },
  {
    name: "v-18a88b0f",
    path: "/en/reading/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18a88b0f").then(next)
    },
  },
  {
    path: "/en/reading/index.html",
    redirect: "/en/reading/"
  },
  {
    path: "/en/Reading/",
    redirect: "/en/reading/"
  },
  {
    name: "v-0e3bb8bc",
    path: "/en/test/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e3bb8bc").then(next)
    },
  },
  {
    path: "/en/test/index.html",
    redirect: "/en/test/"
  },
  {
    path: "/en/Reading/test.html",
    redirect: "/en/test/"
  },
  {
    name: "v-09e593da",
    path: "/en/test2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09e593da").then(next)
    },
  },
  {
    path: "/en/test2/index.html",
    redirect: "/en/test2/"
  },
  {
    path: "/en/Reading/test2.html",
    redirect: "/en/test2/"
  },
  {
    name: "v-453f2d9c",
    path: "/en/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-453f2d9c").then(next)
    },
  },
  {
    path: "/en/vuepress/index.html",
    redirect: "/en/vuepress/"
  },
  {
    path: "/en/Web/vuepress.html",
    redirect: "/en/vuepress/"
  },
  {
    name: "v-107c0742",
    path: "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-107c0742").then(next)
    },
  },
  {
    path: "/en/如何阅读一本书/",
    redirect: "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    path: "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/index.html",
    redirect: "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    path: "/en/Reading/如何阅读一本书.html",
    redirect: "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    name: "v-2392aedc",
    path: "/en/markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2392aedc").then(next)
    },
  },
  {
    path: "/en/markdown/index.html",
    redirect: "/en/markdown/"
  },
  {
    path: "/en/Web/markdown.html",
    redirect: "/en/markdown/"
  },
  {
    name: "v-6e2d7748",
    path: "/en/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e2d7748").then(next)
    },
  },
  {
    path: "/en/html/index.html",
    redirect: "/en/html/"
  },
  {
    path: "/en/Web/html.html",
    redirect: "/en/html/"
  },
  {
    name: "v-f46f11e8",
    path: "/en/introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f46f11e8").then(next)
    },
  },
  {
    path: "/en/introduce/index.html",
    redirect: "/en/introduce/"
  },
  {
    path: "/en/Web/introduce.html",
    redirect: "/en/introduce/"
  },
  {
    name: "v-26e9470f",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26e9470f").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-443319ef",
    path: "/zh/reading/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-443319ef").then(next)
    },
  },
  {
    path: "/zh/reading/index.html",
    redirect: "/zh/reading/"
  },
  {
    path: "/zh/Reading/",
    redirect: "/zh/reading/"
  },
  {
    name: "v-a245f940",
    path: "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a245f940").then(next)
    },
  },
  {
    path: "/zh/高效能人士的七个习惯/",
    redirect: "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    path: "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/index.html",
    redirect: "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    path: "/zh/Reading/高效能人士的七个习惯.html",
    redirect: "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    name: "v-1a955d56",
    path: "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a955d56").then(next)
    },
  },
  {
    path: "/zh/如何阅读一本书/",
    redirect: "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    path: "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/index.html",
    redirect: "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    path: "/zh/Reading/如何阅读一本书.html",
    redirect: "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
  },
  {
    name: "v-d0489880",
    path: "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0489880").then(next)
    },
  },
  {
    path: "/en/高效能人士的七个习惯/",
    redirect: "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    path: "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/index.html",
    redirect: "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    path: "/en/Reading/高效能人士的七个习惯.html",
    redirect: "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]