/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon2.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "望星空, Stargaze, 王怀瑾, Wanghuaijin, Wang Huaijin"
      }
    ],
    [
      "script",
      {},
      "\n        var _hmt = _hmt || [];\n        (function() {\n          var hm = document.createElement(\"script\");\n          hm.src = \"https://hm.baidu.com/hm.js?2675818a983a3131404cee835018f016\";\n          var s = document.getElementsByTagName(\"script\")[0]; \n          s.parentNode.insertBefore(hm, s);\n        })();\n      "
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "sidebar": false,
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2024-08-09T12:12:51.000Z"
          },
          {
            "property": "og:title",
            "content": "Home"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//vuepress-site/"
          },
          {
            "name": "twitter:title",
            "content": "Home"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//vuepress-site/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-835237c2",
      "path": "/vuepress-site/",
      "lastUpdated": "8/9/2024, 8:12:51 PM",
      "lastUpdatedTimestamp": 1723205571000
    },
    {
      "title": "Home",
      "frontmatter": {
        "permalink": "/",
        "home": true,
        "sidebar": false,
        "meta": [
          {
            "property": "og:title",
            "content": "Home"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/"
          },
          {
            "name": "twitter:title",
            "content": "Home"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-7dd379a2",
      "path": "/en/",
      "headers": [
        {
          "level": 2,
          "title": "Contents",
          "slug": "contents"
        },
        {
          "level": 2,
          "title": "Reading",
          "slug": "reading"
        },
        {
          "level": 2,
          "title": "Mathematics",
          "slug": "mathematics"
        },
        {
          "level": 2,
          "title": "Codes",
          "slug": "codes"
        },
        {
          "level": 2,
          "title": "Photography",
          "slug": "photography"
        },
        {
          "level": 2,
          "title": "Audio",
          "slug": "audio"
        },
        {
          "level": 2,
          "title": "Signal",
          "slug": "signal"
        },
        {
          "level": 2,
          "title": "About",
          "slug": "about"
        }
      ]
    },
    {
      "title": "Gallery",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "Gallery"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/photography/"
          },
          {
            "name": "twitter:title",
            "content": "Gallery"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/photography/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Photography/",
      "relativePath": "en/Photography/README.md",
      "key": "v-c1190922",
      "path": "/en/photography/"
    },
    {
      "title": "GTD",
      "frontmatter": {
        "title": "GTD",
        "lang": "zh-CN",
        "meta": [
          {
            "property": "og:title",
            "content": "GTD"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/gtd/"
          },
          {
            "name": "twitter:title",
            "content": "GTD"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/gtd/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Reading/GTD.html",
      "relativePath": "en/Reading/GTD.md",
      "key": "v-6ef466ec",
      "path": "/en/gtd/",
      "headers": [
        {
          "level": 2,
          "title": "Notes",
          "slug": "notes"
        },
        {
          "level": 3,
          "title": "为什么要清空大脑",
          "slug": "为什么要清空大脑"
        },
        {
          "level": 4,
          "title": "1. 大脑负担过重",
          "slug": "_1-大脑负担过重"
        },
        {
          "level": 4,
          "title": "2. 大脑并不总是那么管用",
          "slug": "_2-大脑并不总是那么管用"
        },
        {
          "level": 3,
          "title": "如果不清空大脑会有什么后果",
          "slug": "如果不清空大脑会有什么后果"
        },
        {
          "level": 4,
          "title": "1. 事情总是萦绕在心头",
          "slug": "_1-事情总是萦绕在心头"
        },
        {
          "level": 4,
          "title": "2. 难以进入“心如止水”状态",
          "slug": "_2-难以进入-心如止水-状态"
        },
        {
          "level": 3,
          "title": "清空大脑后的预期——心如止水",
          "slug": "清空大脑后的预期-心如止水"
        },
        {
          "level": 3,
          "title": "如何清空",
          "slug": "如何清空"
        }
      ]
    },
    {
      "title": "After Work",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "After Work"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/afterwork/"
          },
          {
            "name": "twitter:title",
            "content": "After Work"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/afterwork/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Photography/AfterWork.html",
      "relativePath": "en/Photography/AfterWork.md",
      "key": "v-f96ef6c4",
      "path": "/en/afterwork/",
      "headers": [
        {
          "level": 2,
          "title": "Landscape",
          "slug": "landscape"
        }
      ]
    },
    {
      "title": "Vipassana",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "Vipassana"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/vipassana/"
          },
          {
            "name": "twitter:title",
            "content": "Vipassana"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/vipassana/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Photography/Vipassana.html",
      "relativePath": "en/Photography/Vipassana.md",
      "key": "v-2a808650",
      "path": "/en/vipassana/"
    },
    {
      "title": "here is web module",
      "frontmatter": {
        "title": "here is web module",
        "meta": [
          {
            "property": "og:title",
            "content": "here is web module"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/web/"
          },
          {
            "name": "twitter:title",
            "content": "here is web module"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/web/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Web/",
      "relativePath": "en/Web/README.md",
      "key": "v-7e43dee2",
      "path": "/en/web/"
    },
    {
      "title": "Reading",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "Reading"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/reading/"
          },
          {
            "name": "twitter:title",
            "content": "Reading"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/reading/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Reading/",
      "relativePath": "en/Reading/README.md",
      "key": "v-18a88b0f",
      "path": "/en/reading/"
    },
    {
      "title": "Test",
      "frontmatter": {
        "title": "Test",
        "lang": "zh-CN",
        "description": "Here is a test",
        "tags": [
          "test",
          "highlight"
        ],
        "prev": true,
        "meta": [
          {
            "property": "og:title",
            "content": "Test"
          },
          {
            "property": "og:description",
            "content": "Here is a test"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/test/"
          },
          {
            "name": "twitter:title",
            "content": "Test"
          },
          {
            "name": "twitter:description",
            "content": "Here is a test"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/test/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "test, highlight"
          },
          {
            "property": "article:tag",
            "content": "test"
          },
          {
            "property": "article:tag",
            "content": "highlight"
          }
        ]
      },
      "regularPath": "/en/Reading/test.html",
      "relativePath": "en/Reading/test.md",
      "key": "v-0e3bb8bc",
      "path": "/en/test/",
      "headers": [
        {
          "level": 2,
          "title": "Integral Formula",
          "slug": "integral-formula"
        },
        {
          "level": 2,
          "title": "Pythagorean Theorem",
          "slug": "pythagorean-theorem"
        },
        {
          "level": 2,
          "title": "1",
          "slug": "_1"
        },
        {
          "level": 2,
          "title": "2",
          "slug": "_2"
        },
        {
          "level": 2,
          "title": "s3",
          "slug": "s3"
        }
      ]
    },
    {
      "title": "Test2",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "Test2"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/test2/"
          },
          {
            "name": "twitter:title",
            "content": "Test2"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/test2/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Reading/test2.html",
      "relativePath": "en/Reading/test2.md",
      "key": "v-09e593da",
      "path": "/en/test2/"
    },
    {
      "title": "VuePress",
      "frontmatter": {
        "title": "VuePress",
        "collapsable": true,
        "meta": [
          {
            "property": "og:title",
            "content": "VuePress"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/vuepress/"
          },
          {
            "name": "twitter:title",
            "content": "VuePress"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/vuepress/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Web/vuepress.html",
      "relativePath": "en/Web/vuepress.md",
      "key": "v-453f2d9c",
      "path": "/en/vuepress/",
      "headers": [
        {
          "level": 2,
          "title": "快速上手",
          "slug": "快速上手"
        },
        {
          "level": 3,
          "title": "安装环境",
          "slug": "安装环境"
        },
        {
          "level": 3,
          "title": "本地编译",
          "slug": "本地编译"
        },
        {
          "level": 3,
          "title": "部署到Github Pages",
          "slug": "部署到github-pages"
        },
        {
          "level": 4,
          "title": "1. 打包代码",
          "slug": "_1-打包代码"
        },
        {
          "level": 4,
          "title": "2. 推送到远程仓库",
          "slug": "_2-推送到远程仓库"
        },
        {
          "level": 4,
          "title": "3. 启动 Github Pages",
          "slug": "_3-启动-github-pages"
        },
        {
          "level": 4,
          "title": "4. 一键部署脚本",
          "slug": "_4-一键部署脚本"
        },
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "多语言模式",
          "slug": "多语言模式"
        },
        {
          "level": 3,
          "title": "修改主题样式",
          "slug": "修改主题样式"
        },
        {
          "level": 4,
          "title": "修改主题的默认颜色",
          "slug": "修改主题的默认颜色"
        },
        {
          "level": 4,
          "title": "修改各级标题颜色",
          "slug": "修改各级标题颜色"
        },
        {
          "level": 4,
          "title": "修改url的颜色",
          "slug": "修改url的颜色"
        },
        {
          "level": 4,
          "title": "修改目录的颜色",
          "slug": "修改目录的颜色"
        },
        {
          "level": 4,
          "title": "修改索引项的悬停颜色",
          "slug": "修改索引项的悬停颜色"
        },
        {
          "level": 6,
          "title": "KK_LL",
          "slug": "kk-ll"
        },
        {
          "level": 3,
          "title": "Vue 组件",
          "slug": "vue-组件"
        },
        {
          "level": 4,
          "title": "LaTeX插件",
          "slug": "latex插件"
        },
        {
          "level": 4,
          "title": "LaTeX公式块编号",
          "slug": "latex公式块编号"
        },
        {
          "level": 4,
          "title": "Markdown 文本加密",
          "slug": "markdown-文本加密"
        },
        {
          "level": 5,
          "title": "1. 使用npm安装完该插件后，在.vuepress/config.ts文件中更新配置：",
          "slug": "_1-使用npm安装完该插件后-在-vuepress-config-ts文件中更新配置"
        }
      ]
    },
    {
      "title": "如何阅读一本书",
      "frontmatter": {
        "mathjax": {
          "presets": "\\def\\lr#1#2#3{\\left#1#2\\right#3}\\int\\begin\\end\\be\\ee"
        },
        "meta": [
          {
            "property": "og:title",
            "content": "如何阅读一本书"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
          },
          {
            "name": "twitter:title",
            "content": "如何阅读一本书"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Reading/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6.html",
      "relativePath": "en/Reading/如何阅读一本书.md",
      "key": "v-107c0742",
      "path": "/en/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/",
      "headers": [
        {
          "level": 2,
          "title": "这本书的主要内容",
          "slug": "这本书的主要内容"
        },
        {
          "level": 4,
          "title": "内容一：这是什么？",
          "slug": "内容一-这是什么"
        },
        {
          "level": 3,
          "title": "内容二：这又是什么？",
          "slug": "内容二-这又是什么"
        }
      ]
    },
    {
      "title": "Markdown",
      "frontmatter": {
        "title": "Markdown",
        "meta": [
          {
            "property": "og:title",
            "content": "Markdown"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/markdown/"
          },
          {
            "name": "twitter:title",
            "content": "Markdown"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/markdown/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Web/markdown.html",
      "relativePath": "en/Web/markdown.md",
      "key": "v-2392aedc",
      "path": "/en/markdown/"
    },
    {
      "title": "HTML",
      "frontmatter": {
        "title": "HTML",
        "meta": [
          {
            "property": "og:title",
            "content": "HTML"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/html/"
          },
          {
            "name": "twitter:title",
            "content": "HTML"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/html/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Web/html.html",
      "relativePath": "en/Web/html.md",
      "key": "v-6e2d7748",
      "path": "/en/html/"
    },
    {
      "title": "Introduction",
      "frontmatter": {
        "title": "Introduction",
        "meta": [
          {
            "property": "og:title",
            "content": "Introduction"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/introduce/"
          },
          {
            "name": "twitter:title",
            "content": "Introduction"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/introduce/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Web/introduce.html",
      "relativePath": "en/Web/introduce.md",
      "key": "v-f46f11e8",
      "path": "/en/introduce/",
      "headers": [
        {
          "level": 2,
          "title": "关于个人网站",
          "slug": "关于个人网站"
        },
        {
          "level": 2,
          "title": "为什么是VuePress",
          "slug": "为什么是vuepress"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "permalink": "/",
        "home": true,
        "sidebar": false,
        "meta": [
          {
            "property": "og:title",
            "content": "Home"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/"
          },
          {
            "name": "twitter:title",
            "content": "Home"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-26e9470f",
      "path": "/zh/",
      "headers": [
        {
          "level": 2,
          "title": "内容",
          "slug": "内容"
        },
        {
          "level": 2,
          "title": "阅读",
          "slug": "阅读"
        },
        {
          "level": 2,
          "title": "数学",
          "slug": "数学"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "摄影",
          "slug": "摄影"
        },
        {
          "level": 2,
          "title": "音频",
          "slug": "音频"
        },
        {
          "level": 2,
          "title": "信号",
          "slug": "信号"
        },
        {
          "level": 2,
          "title": "关于",
          "slug": "关于"
        }
      ]
    },
    {
      "title": "README",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "README"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/reading/"
          },
          {
            "name": "twitter:title",
            "content": "README"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/reading/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/zh/Reading/",
      "relativePath": "zh/Reading/README.md",
      "key": "v-443319ef",
      "path": "/zh/reading/"
    },
    {
      "title": "高效能人士的七个习惯",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "高效能人士的七个习惯"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
          },
          {
            "name": "twitter:title",
            "content": "高效能人士的七个习惯"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/zh/Reading/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF.html",
      "relativePath": "zh/Reading/高效能人士的七个习惯.md",
      "key": "v-a245f940",
      "path": "/zh/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/",
      "headers": [
        {
          "level": 2,
          "title": "这本书的主要内容",
          "slug": "这本书的主要内容"
        },
        {
          "level": 3,
          "title": "内容一",
          "slug": "内容一"
        },
        {
          "level": 4,
          "title": "1.1",
          "slug": "_1-1"
        },
        {
          "level": 4,
          "title": "1.2",
          "slug": "_1-2"
        },
        {
          "level": 4,
          "title": "1.3",
          "slug": "_1-3"
        },
        {
          "level": 3,
          "title": "内容二",
          "slug": "内容二"
        }
      ]
    },
    {
      "title": "如何阅读一本书",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "如何阅读一本书"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
          },
          {
            "name": "twitter:title",
            "content": "如何阅读一本书"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/zh/Reading/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6.html",
      "relativePath": "zh/Reading/如何阅读一本书.md",
      "key": "v-1a955d56",
      "path": "/zh/%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E4%B8%80%E6%9C%AC%E4%B9%A6/",
      "headers": [
        {
          "level": 2,
          "title": "这本书的主要内容",
          "slug": "这本书的主要内容"
        },
        {
          "level": 4,
          "title": "内容一：这是什么？",
          "slug": "内容一-这是什么"
        },
        {
          "level": 3,
          "title": "内容二：这又是什么？",
          "slug": "内容二-这又是什么"
        }
      ]
    },
    {
      "title": "高效能人士的七个习惯",
      "frontmatter": {
        "meta": [
          {
            "property": "og:title",
            "content": "高效能人士的七个习惯"
          },
          {
            "property": "og:type",
            "content": "article"
          },
          {
            "property": "og:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
          },
          {
            "name": "twitter:title",
            "content": "高效能人士的七个习惯"
          },
          {
            "name": "twitter:url",
            "content": "https://github.com/ciaotomorrow/blog/cn//en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          },
          {
            "name": "twitter:label1",
            "content": "Written by"
          },
          {
            "name": "twitter:label2",
            "content": "Filed under"
          },
          {
            "name": "twitter:data2",
            "content": "Study, Mathematics, Computer"
          },
          {
            "property": "article:tag",
            "content": "Study"
          },
          {
            "property": "article:tag",
            "content": "Mathematics"
          },
          {
            "property": "article:tag",
            "content": "Computer"
          }
        ]
      },
      "regularPath": "/en/Reading/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF.html",
      "relativePath": "en/Reading/高效能人士的七个习惯.md",
      "key": "v-d0489880",
      "path": "/en/%E9%AB%98%E6%95%88%E8%83%BD%E4%BA%BA%E5%A3%AB%E7%9A%84%E4%B8%83%E4%B8%AA%E4%B9%A0%E6%83%AF/",
      "headers": [
        {
          "level": 2,
          "title": "这本书的主要内容",
          "slug": "这本书的主要内容"
        },
        {
          "level": 3,
          "title": "内容一",
          "slug": "内容一"
        },
        {
          "level": 4,
          "title": "1.1",
          "slug": "_1-1"
        },
        {
          "level": 4,
          "title": "1.2",
          "slug": "_1-2"
        },
        {
          "level": 4,
          "title": "1.3",
          "slug": "_1-3"
        },
        {
          "level": 3,
          "title": "内容二",
          "slug": "内容二"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo2.png",
    "sidebar": false,
    "lastUpdated": "Last updated",
    "locales": {
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "ariaLabel": "Languages",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "ALL",
            "items": [
              {
                "text": "Reading",
                "link": "/en/Reading/"
              },
              {
                "text": "Mathematics",
                "link": "/en/Mathematics/"
              },
              {
                "text": "Photography",
                "link": "/en/Photography/"
              },
              {
                "text": "Web",
                "link": "/en/Web/"
              }
            ]
          },
          {
            "text": "Reading",
            "link": "/en/Reading/"
          },
          {
            "text": "Mathematics",
            "link": "/en/Mathematics/"
          },
          {
            "text": "Web",
            "link": "/en/Web/"
          }
        ],
        "sidebar": {
          "/en/Reading/": [
            "",
            {
              "title": "Time Management",
              "collapsable": true,
              "children": [
                "/en/Reading/高效能人士的七个习惯.md",
                "/en/Reading/GTD.md"
              ]
            },
            {
              "title": "Techniques",
              "collapsable": true,
              "children": [
                "/en/Reading/如何阅读一本书.md",
                {
                  "title": "Time Management",
                  "collapsable": true,
                  "children": [
                    "/en/Reading/高效能人士的七个习惯.md",
                    "/en/Reading/GTD.md",
                    "/en/Reading/test.md",
                    "/en/Reading/test2.md"
                  ]
                }
              ]
            }
          ],
          "/en/Photography/": [
            "",
            {
              "title": "Photography",
              "collapsable": true,
              "children": [
                "/en/Photography/AfterWork.md",
                "/en/Photography/Vipassana.md"
              ]
            }
          ],
          "/en/Web/": [
            "",
            {
              "title": "Web",
              "collapsable": true,
              "children": [
                "/en/Web/introduce.md",
                "/en/Web/vuepress.md",
                "/en/Web/markdown.md",
                "/en/Web/html.md"
              ]
            }
          ],
          "/": "auto"
        }
      },
      "/zh/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "ariaLabel": "选择语言",
        "editLinkText": "在 GitHub 上编辑此页",
        "lastUpdated": "最后更新",
        "nav": [
          {
            "text": "阅读",
            "link": "/zh/Reading/"
          },
          {
            "text": "数学",
            "link": "/zh/Mathematics/"
          }
        ],
        "sidebar": {
          "/zh/Reading/": [
            "",
            {
              "title": "阅读",
              "collapsable": true,
              "children": [
                "高效能人士的七个习惯.md",
                "如何阅读一本书.md"
              ]
            }
          ],
          "/": "auto"
        }
      }
    }
  },
  "locales": {
    "/en/": {
      "lang": "en-US",
      "title": "Stargaze",
      "description": "Description in English",
      "path": "/en/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "望星空",
      "description": "中文描述",
      "path": "/zh/"
    }
  }
}